services:
  - type: web
    name: djangoapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lss.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
