services:
  - type: web
    name: lss
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn lss.wsgi:application --bind 0.0.0.0:10000

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lss.settings
      - key: SECRET_KEY
        value: "s4x*u3sk@n#5#1+=97wyt2!)e@z8+@ujr-0o0km1b6$!+ox32f"
      - key: DEBUG
        value: "False"
