services:
  - type: web
    name: djangoapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lss.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lss.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
